### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by ghost** [HughIsaacs2/Cordova-Android-LiveWallpaper#1]
Any progress on this? What else is needed to implement this functionality?

**Comment by HughIsaacs2** [comment]
Too much for me to handle lol.

It's not exactly abandoned, but I've got a bit to learn before I can finish this.

Basically you can't embed a WebView in a Live Wallpaper, so I have to create some sort of custom replacement.

My plan was to simply have this add the Live Wallpaper component to a Cordova project and then have [Microsoft Ace](https://github.com/Microsoft/ace) handle the rest, or embed something like [WebGLGap](https://github.com/AshleyScirra/WebGLGap) in the Live Wallpaper so that someone could just code Canvas/WebGL stuff for building Live Wallpapers.

I'll get around to it at some point, just likely not soon.

**Comment by ghost** [comment]
Oh I see. Sorry I didn't reply sooner, I just saw this? Weird..
